Dataset:
  Fundamental:
    Dir: ./dataset/Fundamental/
    TreeType: ['Binary', 'Normal']
    InputMode: ['edge', 'hierarchy']
    Difficulty: ['easy', 'medium', 'hard']
    Balance: ['balanced', 'unbalanced']
    Weight: ['weighted', 'unweighted']
    SubTask: 
      Normal: ['add_node', 'all_ancestor', 'all_children', 'common_ancestor', 'isomorphic', 'remove_node', 'node_depth', 'leaf', 'root']
      Binary: ['balance', 'prefix_traversal', 'infix_traversal', 'postfix_traversal', 'traversal_order_verification', 'mirror_tree']
  JSON:
    Dir: ./dataset/JSON/
    SubTask: ['child_count', 'node_depth', 'level_count', 'node_relationship', 'node_attribute', 'level_nodes', 'path_down_to_up', 'path_up_to_down', 'shared_ancestor_same_level', 'shared_ancestor_diff_level', 'path_between_nodes']
    Domain: ['university_structure_large_1', 'university_structure_large_2', 'university_structure_medium_1', 'university_structure_medium_2', 'university_structure_small','university_bullshit_structure_large_1', 'university_bullshit_structure_medium_1', 'university_bullshit_structure_large_2', 'university_bullshit_structure_medium_2', 'university_bullshit_structure_small']
  Formula:
    Dir: ./dataset/Formula/
    SubTask: ['calculate', 'convert', 'equivalent']
    Format: ['Infix', 'Prefix', 'Postfix']
    Symbol_Mode: ['easy', 'medium', 'hard']
    Value_Mode: ['easy', 'medium', 'hard']
    Length_Mode: ['easy', 'medium', 'hard']
  Code:
    Dir: ./dataset/Code/
    SubTask: ['SpaceComplexity', 'TimeComplexity', 'CodeMissing']
    Domain: ['Python', 'C++']
    
  Paper:
    Dir: ./dataset/Paper/
    SubTask: ['contextual_qa', 'disordered_section', 'outline_extraction']
    Mode: ['dev', 'test', 'train']

Eval:
  SaveDir: ./Results/