Fundamental:
  SystemTemplate: "As an AI agent, you are tasked with performing hierarchical structure reasoning to assist in understanding and analyzing complex organizational frameworks."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE> and do not feedback the detailed process."
  Task:
    Normal:
      add_node:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>."
        OutputFormatTemplate: "{\"answer\": <new structure>} following the input structure format,"
      all_ancestor: 
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID of ancestors and split by comma, if there is no ancestors, please return {\"answer\": None}"
      all_children:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID of children nodes and split by comma, if there is no children nodes, please return {\"answer\": None}"
      common_ancestor:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1}, where 1 is the node ID,"
      isomorphic:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE_#0>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": true} if it is isomorphic, or {\"answer\": false} if it is not,"
      remove_node:
        PrefixPromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": <new structure>} following the input structure format,"
      node_depth:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1}, where 1 is the node's depth,"
      leaf:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": true} if it is leaf node, or {\"answer\": false} if it is not,"
      root:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1}, where 1 is the node ID,"
    Binary:
      Balance: 
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": true} if it is a balance binary tree, or {\"answer\": false} if it is not,"
      PrefixTraversal:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID in prefix traversal order and split by comma,"
      InfixTraversal:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID in infix traversal order and split by comma,"
      PostfixTraversal:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID in postfix traversal order and split by comma,"
      TraversalOrderVerification:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": preorder} if it is the preorder, {\"answer\": inorder} if it is the inorder, and {\"answer\": postorder} if it is the postorder."
      MirrorTree:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": <new structure>} following the input structure format,"

JSON:
  SystemTemplate: "As an AI agent, you are tasked with performing hierarchical structure reasoning to assist in understanding and analyzing complex organizational frameworks."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE>  and do not feedback the detailed process."
  Task:
    Task1:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": 1}"
    Task2:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": \"Employees\"}"
    Task3:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": 1}"
    Task4:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": \"True\"}"
    Task5:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": \"XXX\"}"

Formula:
  SystemTemplate: "As an AI agent, you are tasked with performing mathematical reasoning to assist in solving complex mathematical problems."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE>  and do not feedback the detailed process."
  Task:
    Calculation:
      PromptTemplate: "Given a mathematical formula <FORMULA>, calculate its result."
      OutputFormatTemplate: "{\"answer\": 1}"
    Convert:
      PromptTemplate: "Given a mathematical <FORMAT1> formula <FORMULA>, convert it to <FORMAT2> notation."
      OutputFormatTemplate: "{\"answer\": 319 * 924.20 * ( ( 460 + 352.48 ) + 98 )}"
    Equation:
      PromptTemplate: "Given two mathematical formulas <FORMULA1> and <FORMULA2>, determine if they are equivalent."
      OutputFormatTemplate: "{\"answer\": \"True\"}"

Code:
  SystemTemplate: "As an AI agent, you are tasked with performing code reasoning to assist in understanding and analyzing complex code snippets."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE>  and do not feedback the detailed process."
  Task:
    SpaceComplexity:
      PromptTemplate: "Given a code snippet <CODE>, calculate its space complexity."
      OutputFormatTemplate: "{\"answer\":  O(1)}"
    TimeComplexity:
      PromptTemplate: "Given a code snippet <CODE>, calculate its time complexity."
      OutputFormatTemplate: "{\"answer\":  O(n)}"
    CodeMissing:
      PromptTemplate: "Given a code snippet <CODE>, please find and write the missing code."
      OutputFormatTemplate: "{\"answer\": \"Line 10: result.append('D' * max(y1-y, 0))\"}"

Paper:
  SystemTemplate: "As an AI agent, you are tasked with performing paper reasoning to assist in understanding and analyzing complex academic papers."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE>  and do not feedback the detailed process."
  Task:
    contextual_qa:
      PromptTemplate: "<QUESTION>"
      OutputFormatTemplate: "{\"answer\": \"XXX\"}"
    disordered_section:
      PromptTemplate: "<QUESTION>"
      OutputFormatTemplate: "{\"answer\": \"XXX\"}"
    outline_extraction:
      PromptTemplate: "<QUESTION>"
      OutputFormatTemplate: "{\"answer\": \"XXX\"}"