OneshotExamplePrompt: "Here is one example.The input is <QUESTION1>, the answer is <ANSWER1>."
FewshotExamplePrompt: "Here are a few examples. The input is <QUESTION1>, the answer is <ANSWER1>. The input is <QUESTION2>, the answer is <ANSWER2>. The input is <QUESTION3>, the answer is <ANSWER3>."
Fundamental:
  SystemTemplate: "As an AI agent, you are tasked with performing hierarchical structure reasoning to assist in understanding and analyzing complex organizational frameworks."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE> and do not feedback the detailed process."
  Task:
    Normal:
      add_node:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": <new structure>} following the input structure format,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      all_ancestor: 
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID of ancestors and split by comma, if there is no ancestors, please return {\"answer\": None}"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      all_children:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID of children nodes and split by comma, if there is no children nodes, please return {\"answer\": None}"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      common_ancestor:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1}, where 1 is the node ID,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      isomorphic:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE_#0>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": true} if it is isomorphic, or {\"answer\": false} if it is not,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      remove_node:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": <new structure>} following the input structure format, if there are no edges, please return {\"answer\": No edges}"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      node_depth:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1}, where 1 is the node's depth,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      leaf:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": true} if it is leaf node, or {\"answer\": false} if it is not,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      root:
        PromptTemplate: "Given the hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1}, where 1 is the node ID,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    Binary:
      balance: 
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": true} if it is a balance binary tree, or {\"answer\": false} if it is not,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      prefix_traversal:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID in prefix traversal order and split by comma,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      infix_traversal:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID in infix traversal order and split by comma,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      postfix_traversal:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": 1, 2, 3}, where 1, 2, and 3 are the node ID in postfix traversal order and split by comma,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
        
      traversal_order_verification:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": preorder} if it is the preorder, {\"answer\": inorder} if it is the inorder, and {\"answer\": postorder} if it is the postorder."
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
      mirror_tree:
        PromptTemplate: "Given the binary tree-liked hierarchical structure <STRUCTURE>, <QUESTION>"
        OutputFormatTemplate: "{\"answer\": <new structure>} following the input structure format,"
        Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"


JSON:
  SystemTemplate: "As an AI agent, you are tasked with performing hierarchical structure reasoning to assist in understanding and analyzing complex organizational frameworks."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE>  and do not feedback the detailed process."
  Task:
    Task1:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": 1}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    Task2:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": \"Employees\"}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    Task3:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": 1}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    Task4:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": \"True\"}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    Task5:
      PromptTemplate: "Given a JSON object <JSON>, <QUESTION>."
      OutputFormatTemplate: "{\"answer\": \"XXX\"}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"

Formula:
  SystemTemplate: "As an AI agent, you are tasked with performing mathematical reasoning to assist in solving complex mathematical problems."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE>  and do not feedback the detailed process."
  Task:
    Calculation:
      PromptTemplate: "Given a mathematical formula <FORMULA>, calculate its result."
      OutputFormatTemplate: "{\"answer\": 1}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    Convert:
      PromptTemplate: "Given a mathematical <FORMAT1> formula <FORMULA>, convert it to <FORMAT2> notation."
      OutputFormatTemplate: "{\"answer\": 319 * 924.20 * ( ( 460 + 352.48 ) + 98 )}"
      Question: "Here is one example."
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    Equation:
      PromptTemplate: "Given two mathematical formulas <FORMULA1> and <FORMULA2>, determine if they are equivalent."
      OutputFormatTemplate: "{\"answer\": \"True\"}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"

Code:
  SystemTemplate: "As an AI agent, you are tasked with performing code reasoning to assist in understanding and analyzing complex code snippets."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE>  and do not feedback the detailed process."
  Task:
    SpaceComplexity:
      PromptTemplate: "Given a code snippet <CODE>, calculate its space complexity."
      OutputFormatTemplate: "{\"answer\":  O(1)}"
      Example: 
          Question1: "class Solution(object):
    def sum(self, num1, num2):
        return num1+num2
        What is the Space Complexity?"
          Answer1: "O(1)"
          Question2: "class Solution(object):
    def addBinary(self, a, b):
        result, carry, val = "", 0, 0
        for i in xrange(max(len(a), len(b))):
            val = carry
            if i < len(a):
                val += int(a[-(i + 1)])
            if i < len(b):
                val += int(b[-(i + 1)])
            carry, val = divmod(val, 2)
            result += str(val)
        if carry:
            result += str(carry)
        return result[::-1]
        What is the Space Complexity?"
          Answer2: "O(1)"
          Question3: "class Solution2(object):
    def arrayPairSum(self, nums):
        nums.sort()
        result = 0
        for i in xrange(0, len(nums), 2):
            result += nums[i]
        return result
        What is the Space Complexity?"
          Answer3: "O(1)"
    TimeComplexity:
      PromptTemplate: "Given a code snippet <CODE>, calculate its time complexity."
      OutputFormatTemplate: "{\"answer\":  O(n)}"
      Example: 
          Question1: "class Solution(object):
    def sum(self, num1, num2):
        return num1+num2
        What is the Time Complexity?"
          Answer1: "O(1)"
          Question2: "class Solution(object):
    def addBinary(self, a, b):
        result, carry, val = "", 0, 0
        for i in xrange(max(len(a), len(b))):
            val = carry
            if i < len(a):
                val += int(a[-(i + 1)])
            if i < len(b):
                val += int(b[-(i + 1)])
            carry, val = divmod(val, 2)
            result += str(val)
        if carry:
            result += str(carry)
        return result[::-1]
        What is the Time Complexity?"
          Answer2: "O(n)"
          Question3: "class Solution2(object):
    def arrayPairSum(self, nums):
        nums.sort()
        result = 0
        for i in xrange(0, len(nums), 2):
            result += nums[i]
        return result
        What is the Time Complexity?"
          Answer3: "O(nlogn)"
    CodeMissing:
      PromptTemplate: "Given a code snippet <CODE>, please find and write the missing code."
      OutputFormatTemplate: "{\"answer\": \"Line 10: result.append('D' * max(y1-y, 0))\"}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"

Paper:
  SystemTemplate: "As an AI agent, you are tasked with performing paper reasoning to assist in understanding and analyzing complex academic papers."
  OutputFormatTemplate: "Please return the answer in JSON format directly like <OUTPUTFORMATE>  and do not feedback the detailed process."
  Task:
    contextual_qa:
      PromptTemplate: "<QUESTION>"
      OutputFormatTemplate: "{\"answer\": \"XXX\"}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    disordered_section:
      PromptTemplate: "<QUESTION>"
      OutputFormatTemplate: "{\"answer\": \"XXX\"}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"
    outline_extraction:
      PromptTemplate: "<QUESTION>"
      OutputFormatTemplate: "{\"answer\": \"XXX\"}"
      Example: 
          Question1: "Q1"
          Answer1: "A1"
          Question2: "Q2"
          Answer2: "A2"
          Question3: "Q3"
          Answer3: "A3"

